### ISSUE TITLE
I tried it with the New Release, its still not working but showing an error.  [BUG]

### ISSUE THREAD

**Issue by Einkornwolf** [CapOliveiraBr/DBM-Firebase#3]
Hey, I really apreciate that you tried to fix the bug so fast! But it still doesnt work...
I get this Error-Code: 

```
Bot is ready!
(node:16692) UnhandledPromiseRejectionWarning: TypeError: this.getMods is not a function
    at Object.action [as Control Firebase Global Data] (C:\Users\Finn\Desktop\DX_Sheet\actions\control_firebase_global_data_MOD.js:49:27)
    at Object.Actions.invokeActions (C:\Users\Finn\Desktop\DX_Sheet\bot.js:498:18)
    at Object.Actions.preformActions (C:\Users\Finn\Desktop\DX_Sheet\bot.js:387:8)
    at Object.Bot.checkCommand (C:\Users\Finn\Desktop\DX_Sheet\bot.js:178:12)
    at Object.Bot.onMessage (C:\Users\Finn\Desktop\DX_Sheet\bot.js:161:13)
    at Client.emit (events.js:311:20)
    at MessageCreateAction.handle (C:\Users\Finn\Desktop\DX_Sheet\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Finn\Desktop\DX_Sheet\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Finn\Desktop\DX_Sheet\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Finn\Desktop\DX_Sheet\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
(node:16692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

I hope you can get something usefull out of that.

Regards Finn

![sheeterror](https://user-images.githubusercontent.com/66327503/87410028-16817200-c5c6-11ea-8b1d-6dc4fe8f121b.PNG)

**Comment by cappp** [comment]
Your DBM Mods are not the latest, you need to update: https://github.com/dbm-network/mods

**Comment by Einkornwolf** [comment]
Oh yeeessss :D Thanks alot mate! Its working now

**Comment by cappp** [comment]
👍
