### ISSUE TITLE
SyntaxError: Unexpected token a in JSON at position 2

### ISSUE THREAD

**Issue by Echo-Script** [CapOliveiraBr/DBM-Firebase#7]
While using Firebase, set up and everything else, there is a syntax error preventing the command from continuing.

**Actions List:**
![image](https://user-images.githubusercontent.com/50340593/87814476-bb68ad00-c85b-11ea-8309-64a1e917aaee.png)

**Error:**
![image](https://user-images.githubusercontent.com/50340593/87814564-e0f5b680-c85b-11ea-9c23-f254cd5f183a.png)

**Comment by cappp** [comment]
The error of the print to me does not seem to be an error of the list of actions that you showed in the print.

**Comment by cappp** [comment]
Probably the file `fbConfig.json` has some syntax problem, can you send me a print of it?

**Comment by Echo-Script** [comment]
I'm a little new to this - Should I blur any parts?

**Comment by cappp** [comment]
Yes.

**Comment by Mexi-0001** [comment]
![image](https://user-images.githubusercontent.com/50340593/87819346-f5d64800-c863-11ea-8077-d47c98e414ad.png)

**Comment by cappp** [comment]
You need to put quotation marks in the keys of the json file. Example:
```json
{
  "apiKey": "X",
  "authDomain": "X",
  "databaseURL": "X",
  "projectId": "X",
  "storageBucket": "X",
  "messagingSenderId": "X",
  "appId": "X"
}
```

**Comment by Echo-Script** [comment]
AH! I'll try it now, thanks

**Comment by Echo-Script** [comment]
`2020-07-17T18:52:14.042080+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Error: permission_denied at /data/players/290274026738286593/Points: Client doesn't have permission to access the desired data.
2020-07-17T18:52:14.042100+00:00 app[worker.1]: at errorForServerCode (/app/node_modules/@firebase/database/dist/index.node.cjs.js:654:17)
2020-07-17T18:52:14.042100+00:00 app[worker.1]: at onComplete (/app/node_modules/@firebase/database/dist/index.node.cjs.js:9063:33)
2020-07-17T18:52:14.042101+00:00 app[worker.1]: at Object.onComplete (/app/node_modules/@firebase/database/dist/index.node.cjs.js:12554:34)
2020-07-17T18:52:14.042102+00:00 app[worker.1]: at /app/node_modules/@firebase/database/dist/index.node.cjs.js:11689:32
2020-07-17T18:52:14.042103+00:00 app[worker.1]: at PersistentConnection.onDataMessage_ (/app/node_modules/@firebase/database/dist/index.node.cjs.js:11929:17)
2020-07-17T18:52:14.042103+00:00 app[worker.1]: at Connection.onDataMessage_ (/app/node_modules/@firebase/database/dist/index.node.cjs.js:11246:14)
2020-07-17T18:52:14.042104+00:00 app[worker.1]: at Connection.onPrimaryMessageReceived_ (/app/node_modules/@firebase/database/dist/index.node.cjs.js:11240:18)
2020-07-17T18:52:14.042104+00:00 app[worker.1]: at WebSocketConnection.onMessage (/app/node_modules/@firebase/database/dist/index.node.cjs.js:11141:27)
2020-07-17T18:52:14.042105+00:00 app[worker.1]: at WebSocketConnection.appendFrame_ (/app/node_modules/@firebase/database/dist/index.node.cjs.js:10727:18)
2020-07-17T18:52:14.042105+00:00 app[worker.1]: at WebSocketConnection.handleIncomingFrame (/app/node_modules/@firebase/database/dist/index.node.cjs.js:10778:22)
2020-07-17T18:52:14.042148+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)



`

**Comment by Echo-Script** [comment]
oh oops seems to be my fault

**Comment by cappp** [comment]
You have created a private database: "Client doesn't have permission to access the desired"

**Comment by cappp** [comment]
Read [this](https://github.com/cappp/dbm-firebase#creating-database) topic.

**Comment by Echo-Script** [comment]
I fixed the permissions, it seems to do nothing to member data or the database

**Comment by Echo-Script** [comment]
there are no console errors either

**Comment by Echo-Script** [comment]
Ok Update: the database shows the values - ill try some experimenting from here

**Comment by cappp** [comment]
I have tested the mods again, and everything is ok, the Firebase have a delay of some seconds to connect when you execute a command with him on the first time.

**Comment by cappp** [comment]
I will close this issue, if soon you have any issue, open a new.

**Comment by Mexi-0001** [comment]
Well - I noticed you can only store one value or you'll get **undefined**
